_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
model_1:
    value: Linear Regression
model_2:
    value: Decision Tree Regressor
random_state:
    value: 42
test_size:
    value: 0.2
